/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

module.exports = {
	CSS: [
		{
			type: "autogenerated",
			dirName: "CSS", // 从 docs/CSS 文件夹自动生成侧边栏切片
		},
	],
	JavaScript: [
		{
			type: "autogenerated",
			dirName: "JavaScript",
		},
	],
	React: [
		{
			type: "autogenerated",
			dirName: "React",
		},
	],
	Tools: [
		{
			type: "autogenerated",
			dirName: "Tools",
		},
		{
			type: "autogenerated",
			dirName: "Others",
		},
	],
};
